version: '3'
services:
  app:
    container_name: react-frontend
    image: node:16-alpine
    tty: true
    volumes:
      - ./:/app
    working_dir: /app
    command: /bin/sh -c "yarn install && /bin/sh"
    ports:
      - '3000:3000'
      - '6006:6006'
    